---
- name: creating a cluster
  hosts: cockroachDB
  tasks: 
    - name: Get internal IP
      shell: ifconfig ens160 | grep  -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"  | head -n1 > /root/internalip.txt
    - name: Get all internal IPs
      command: cat /root/internalip.txt
      register: internalips
      changed_when: false
    - name: creating a cockroachDB cluster
      shell: cockroach init --insecure --host {{ internalips.stdout }} 

